---
entrypoint: uvicorn main:app --reload --host 0.0.0.0 --port 8080
env: flex
runtime: python
runtime_config:
  python_version: 3.7
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 32
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5